services:
  db:
    image: mongo:6.0
    restart: unless-stopped
    env_file: .env
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  web:
    image: node:lts
    # user: 'node' #you can remove this if you are facing access issues when installing node packages
    working_dir: /home/node/app
    env_file: .env
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://admin:secret@db:27017/music_lib?authSouce=admin
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/node/app
    command: 'npm run start'
# This defines our volume(s), which will persist throughout startups.
# If you want to get rid of a hanging volume, e.g. to test your database init,
# run `docker-compose rm -v`. Note that this will remove ALL of your data, so
# be extra sure you've made a stable backup somewhere.
volumes:
  mongo_data: